### ISSUE TITLE
Running the Lingua Franca IDE on macOS Catalina

### ISSUE THREAD

**Issue by lsk567** [icyphy/lingua-franca#179]
There was previously an issue with running the Lingua Franca IDE on macOS Catalina. The problem happens in [Step 4](https://github.com/icyphy/lingua-franca/wiki/Downloading-and-Building#4-run-the-lingua-franca-ide) of "Run the Lingua Franca IDE." After clicking "Run As -> Eclipse Application," Eclipse (version `4.15.0`) throws a `Could not load SWT library` error. The macOS version where this issue occurs is `10.15.4`.

```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/Users/shaokai/lf-workspace/.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/org.eclipse.osgi/407/0/.cp/libswt-cocoa-4932r18.jnilib: dlopen(/Users/shaokai/lf-workspace/.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/org.eclipse.osgi/407/0/.cp/libswt-cocoa-4932r18.jnilib, 1): no suitable image found.  Did find:
	/Users/shaokai/lf-workspace/.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/org.eclipse.osgi/407/0/.cp/libswt-cocoa-4932r18.jnilib: code signature in (/Users/shaokai/lf-workspace/.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/org.eclipse.osgi/407/0/.cp/libswt-cocoa-4932r18.jnilib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	no swt-cocoa in java.library.path: [/Users/shaokai/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib: dlopen(/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib, 1): no suitable image found.  Did find:
	/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib: code signature in (/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
	Can't load library: /Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa.jnilib
	/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib: dlopen(/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib, 1): no suitable image found.  Did find:
	/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib: code signature in (/Users/shaokai/.swt/lib/macosx/x86_64/libswt-cocoa-4932r18.jnilib) not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs

at org.eclipse.swt.internal.Library.loadLibrary(Library.java:342)
at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
at org.eclipse.swt.internal.C.<clinit>(C.java:19)
at org.eclipse.swt.widgets.Display.<clinit>(Display.java:107)
at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:760)
at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:166)
at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:180)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

Eclipse session data
```
eclipse.buildId=4.15.0.I20200305-0155
java.version=12.0.2
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /Users/shaokai/lf-workspace/../runtime-EclipseXtext -dev file:/Users/shaokai/lf-workspace/.metadata/.plugins/org.eclipse.pde.core/Launch Runtime Eclipse/dev.properties -os macosx -ws cocoa -arch x86_64
```

**Comment by lsk567** [comment]
The problem is that when launching an Eclipse application, the plain JVM installed in the environment is used. So far JDK 14 is the only version that supports macOS Catalina's hardened runtime. More detailed info here: https://www.oracle.com/technetwork/java/javase/using-jdk-jre-macos-catalina-5781620.html.

The solution is acquired from an Eclipse forum user. https://www.eclipse.org/forums/index.php/m/1828893/#msg_1828893
