### ISSUE TITLE
NPE in CGenerator

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#238]
Something like this:

```
 reactor Foo {
    input reqIn:bool;
    output resOut:bool;
    reaction(reqIn) resOut {=
        
    =}
}
```

Triggers a NPE in CGenerator:
```
lfc: unexpected error.
java.lang.NullPointerException
	at org.icyphy.generator.CGenerator.generateSelfStruct(CGenerator.java:2592)
	at org.icyphy.generator.CGenerator.generateReactorFederated(CGenerator.java:2029)
	at org.icyphy.generator.CGenerator.doGenerate(CGenerator.java:523)
	at org.icyphy.generator.LinguaFrancaGenerator.doGenerate(LinguaFrancaGenerator.java:72)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:44)
	at org.eclipse.xtext.generator.GeneratorDelegate.generate(GeneratorDelegate.java:35)
	at org.icyphy.generator.Main.runGenerator(Main.java:156)
	at org.icyphy.generator.Main.main(Main.java:43)
```

**Comment by edwardalee** [comment]
I have updated the validator to guard against these sorts of errors, so, now, the code generator will not be invoked on this program.
