### ISSUE TITLE
Stackoverflow in ReactionGraph

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#298]
```
[marten@yoga lingua-franca]$ bin/lfc -r test/Python/src/SimpleImport.lf 
lfc: info: Not rebuilding; already up-to-date.
******** mode: STANDALONE
******** source file: /home/marten/lingua-franca-master/git/lingua-franca/test/Python/src/SimpleImport.lf
******** generated sources: /home/marten/lingua-franca-master/git/lingua-franca/test/Python/src-gen/SimpleImport
******** generated binaries: /home/marten/lingua-franca-master/git/lingua-franca/test/Python/bin
Generating code for: file:/home/marten/lingua-franca-master/git/lingua-franca/test/Python/src/SimpleImport.lf
0    [main] ERROR text.validation.CompositeEValidator  - Error executing EValidator
java.lang.StackOverflowError
	at org.icyphy.ASTUtils.allConnections(ASTUtils.java:643)
	at org.icyphy.graph.ReactionGraph.collectNodesFrom(ReactionGraph.java:74)
	at org.icyphy.graph.ReactionGraph.collectNodesFrom(ReactionGraph.java:214)
	at org.icyphy.graph.ReactionGraph.collectNodesFrom(ReactionGraph.java:214)
	at org.icyphy.graph.ReactionGraph.collectNodesFrom(ReactionGraph.java:214)
	at org.icyphy.graph.ReactionGraph.collectNodesFrom(ReactionGraph.java:214)
```

**Comment by lhstrh** [comment]
The LF code that triggers this:
```
main reactor HelloWorld {
    a = new HelloWorld();
}
```

This is surprising because we have a check for circular instantiations in the validator. This check is clearly not working (anymore).
